"""initial schema

Revision ID: 571fc2261a2e
Revises: 
Create Date: 2026-08-31 09:16:18.255392
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '571fc2261a2e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_uid', sa.String(length=64), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('site', sa.String(length=120), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('reporter_role', sa.String(length=120), nullable=True),
    sa.Column('activity', sa.String(length=160), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index('ix_report_site_date', ['site', 'report_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_activity'), ['activity'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_report_date'), ['report_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_report_uid'), ['report_uid'], unique=True)
        batch_op.create_index(batch_op.f('ix_reports_site'), ['site'], unique=False)

    op.create_table('verdicts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('classification', sa.String(length=32), nullable=False),
    sa.Column('energy_source', sa.String(length=32), nullable=True),
    sa.Column('high_energy', sa.Boolean(), nullable=False),
    sa.Column('high_energy_incident', sa.Boolean(), nullable=False),
    sa.Column('control_status', sa.String(length=32), nullable=False),
    sa.Column('direct_control_key', sa.String(length=64), nullable=True),
    sa.Column('direct_control_effective', sa.Boolean(), nullable=False),
    sa.Column('injury_outcome', sa.String(length=32), nullable=False),
    sa.Column('primary_lsr', sa.String(length=48), nullable=True),
    sa.Column('secondary_lsr', sa.JSON(), nullable=False),
    sa.Column('evidence_completeness', sa.Float(), nullable=False),
    sa.Column('triage_rank', sa.Integer(), nullable=False),
    sa.Column('engine_version', sa.String(length=32), nullable=False),
    sa.Column('extractor_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verdicts', schema=None) as batch_op:
        batch_op.create_index('ix_verdict_site_energy', ['energy_source', 'classification'], unique=False)
        batch_op.create_index(batch_op.f('ix_verdicts_classification'), ['classification'], unique=False)
        batch_op.create_index(batch_op.f('ix_verdicts_control_status'), ['control_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_verdicts_direct_control_key'), ['direct_control_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_verdicts_energy_source'), ['energy_source'], unique=False)
        batch_op.create_index(batch_op.f('ix_verdicts_evidence_completeness'), ['evidence_completeness'], unique=False)
        batch_op.create_index(batch_op.f('ix_verdicts_injury_outcome'), ['injury_outcome'], unique=False)
        batch_op.create_index(batch_op.f('ix_verdicts_primary_lsr'), ['primary_lsr'], unique=False)
        batch_op.create_index(batch_op.f('ix_verdicts_report_id'), ['report_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_verdicts_triage_rank'), ['triage_rank'], unique=False)

    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('verdict_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_role', sa.String(length=120), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('corrected_classification', sa.String(length=32), nullable=True),
    sa.Column('corrected_energy_source', sa.String(length=32), nullable=True),
    sa.Column('corrected_control_status', sa.String(length=32), nullable=True),
    sa.Column('corrected_primary_lsr', sa.String(length=48), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verdict_id'], ['verdicts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_corrected_classification'), ['corrected_classification'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_decision'), ['decision'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_report_id'), ['report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_verdict_id'), ['verdict_id'], unique=False)

    op.create_table('rule_firings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('verdict_id', sa.Integer(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('conclusion', sa.Text(), nullable=False),
    sa.Column('citation_key', sa.String(length=48), nullable=False),
    sa.ForeignKeyConstraint(['verdict_id'], ['verdicts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rule_firings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_firings_rule_id'), ['rule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_firings_verdict_id'), ['verdict_id'], unique=False)

    op.create_table('evidence_spans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('verdict_id', sa.Integer(), nullable=False),
    sa.Column('rule_firing_id', sa.Integer(), nullable=True),
    sa.Column('start_char', sa.Integer(), nullable=False),
    sa.Column('end_char', sa.Integer(), nullable=False),
    sa.Column('quoted_text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['rule_firing_id'], ['rule_firings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verdict_id'], ['verdicts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence_spans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_spans_rule_firing_id'), ['rule_firing_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_spans_verdict_id'), ['verdict_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidence_spans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_spans_verdict_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_spans_rule_firing_id'))

    op.drop_table('evidence_spans')
    with op.batch_alter_table('rule_firings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_firings_verdict_id'))
        batch_op.drop_index(batch_op.f('ix_rule_firings_rule_id'))

    op.drop_table('rule_firings')
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_verdict_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_report_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_decision'))
        batch_op.drop_index(batch_op.f('ix_reviews_created_at'))
        batch_op.drop_index(batch_op.f('ix_reviews_corrected_classification'))

    op.drop_table('reviews')
    with op.batch_alter_table('verdicts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verdicts_triage_rank'))
        batch_op.drop_index(batch_op.f('ix_verdicts_report_id'))
        batch_op.drop_index(batch_op.f('ix_verdicts_primary_lsr'))
        batch_op.drop_index(batch_op.f('ix_verdicts_injury_outcome'))
        batch_op.drop_index(batch_op.f('ix_verdicts_evidence_completeness'))
        batch_op.drop_index(batch_op.f('ix_verdicts_energy_source'))
        batch_op.drop_index(batch_op.f('ix_verdicts_direct_control_key'))
        batch_op.drop_index(batch_op.f('ix_verdicts_control_status'))
        batch_op.drop_index(batch_op.f('ix_verdicts_classification'))
        batch_op.drop_index('ix_verdict_site_energy')

    op.drop_table('verdicts')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_site'))
        batch_op.drop_index(batch_op.f('ix_reports_report_uid'))
        batch_op.drop_index(batch_op.f('ix_reports_report_date'))
        batch_op.drop_index(batch_op.f('ix_reports_activity'))
        batch_op.drop_index('ix_report_site_date')

    op.drop_table('reports')
    # ### end Alembic commands ###
